openapi: 3.2.0
info:
  version: 2.57.0
  title: Netlify's API documentation Split Test API
  description: Netlify is a hosting service for the programmable web.
  termsOfService: https://www.netlify.com/legal/terms-of-use/
  x-logo:
    url: netlify-logo.png
    href: https://www.netlify.com/docs/
    altText: Netlify
servers:
- url: https://api.netlify.com/api/v1
security:
- netlifyAuth: []
tags:
- name: Split Test
  x-displayName: Split test
paths:
  /sites/{site_id}/traffic_splits:
    parameters:
    - name: site_id
      in: path
      required: true
      schema:
        type: string
    post:
      operationId: createSplitTest
      tags:
      - Split Test
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  site_id:
                    type: string
                  name:
                    type: string
                  path:
                    type: string
                  branches:
                    type: array
                    items:
                      type: object
                  active:
                    type: boolean
                  created_at:
                    type: string
                    format: dateTime
                  updated_at:
                    type: string
                    format: dateTime
                  unpublished_at:
                    type: string
                    format: dateTime
        default:
          description: error
          content:
            application/json:
              schema:
                type: object
                required:
                - message
                properties:
                  code:
                    type: integer
                    format: int64
                  message:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                branch_tests:
                  type: object
        required: true
      summary: Create split test
      x-summary-source: derived
    get:
      operationId: getSplitTests
      tags:
      - Split Test
      responses:
        '200':
          description: split_tests
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    site_id:
                      type: string
                    name:
                      type: string
                    path:
                      type: string
                    branches:
                      type: array
                      items:
                        type: object
                    active:
                      type: boolean
                    created_at:
                      type: string
                      format: dateTime
                    updated_at:
                      type: string
                      format: dateTime
                    unpublished_at:
                      type: string
                      format: dateTime
        default:
          description: error
          content:
            application/json:
              schema:
                type: object
                required:
                - message
                properties:
                  code:
                    type: integer
                    format: int64
                  message:
                    type: string
      summary: Get split tests
      x-summary-source: derived
  /sites/{site_id}/traffic_splits/{split_test_id}:
    parameters:
    - name: site_id
      in: path
      required: true
      schema:
        type: string
    - name: split_test_id
      in: path
      required: true
      schema:
        type: string
    put:
      operationId: updateSplitTest
      tags:
      - Split Test
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  site_id:
                    type: string
                  name:
                    type: string
                  path:
                    type: string
                  branches:
                    type: array
                    items:
                      type: object
                  active:
                    type: boolean
                  created_at:
                    type: string
                    format: dateTime
                  updated_at:
                    type: string
                    format: dateTime
                  unpublished_at:
                    type: string
                    format: dateTime
        default:
          description: error
          content:
            application/json:
              schema:
                type: object
                required:
                - message
                properties:
                  code:
                    type: integer
                    format: int64
                  message:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                branch_tests:
                  type: object
        required: true
      summary: Update split test
      x-summary-source: derived
    get:
      operationId: getSplitTest
      tags:
      - Split Test
      responses:
        '200':
          description: split_test
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  site_id:
                    type: string
                  name:
                    type: string
                  path:
                    type: string
                  branches:
                    type: array
                    items:
                      type: object
                  active:
                    type: boolean
                  created_at:
                    type: string
                    format: dateTime
                  updated_at:
                    type: string
                    format: dateTime
                  unpublished_at:
                    type: string
                    format: dateTime
        default:
          description: error
          content:
            application/json:
              schema:
                type: object
                required:
                - message
                properties:
                  code:
                    type: integer
                    format: int64
                  message:
                    type: string
      summary: Get split test
      x-summary-source: derived
  /sites/{site_id}/traffic_splits/{split_test_id}/publish:
    parameters:
    - name: site_id
      in: path
      required: true
      schema:
        type: string
    - name: split_test_id
      in: path
      required: true
      schema:
        type: string
    post:
      operationId: enableSplitTest
      tags:
      - Split Test
      responses:
        '204':
          description: enable
        default:
          description: error
          content:
            application/json:
              schema:
                type: object
                required:
                - message
                properties:
                  code:
                    type: integer
                    format: int64
                  message:
                    type: string
      summary: Enable split test
      x-summary-source: derived
  /sites/{site_id}/traffic_splits/{split_test_id}/unpublish:
    parameters:
    - name: site_id
      in: path
      required: true
      schema:
        type: string
    - name: split_test_id
      in: path
      required: true
      schema:
        type: string
    post:
      operationId: disableSplitTest
      tags:
      - Split Test
      responses:
        '204':
          description: disabled
        default:
          description: error
          content:
            application/json:
              schema:
                type: object
                required:
                - message
                properties:
                  code:
                    type: integer
                    format: int64
                  message:
                    type: string
      summary: Disable split test
      x-summary-source: derived
components:
  securitySchemes:
    netlifyAuth:
      type: oauth2
      flows:
        implicit:
          scopes: {}
          authorizationUrl: https://app.netlify.com/authorize
externalDocs:
  url: https://www.netlify.com/docs/api/
  description: Online documentation
x-tagGroups:
- name: OAuth
  tags:
  - ticket
  - accessToken
- name: User accounts
  tags:
  - user
  - accountMembership
  - member
  - accountType
  - paymentMethod
  - auditLog
- name: Site
  tags:
  - site
  - environmentVariables
  - file
  - metadata
  - purge
  - snippet
- name: Domain names
  tags:
  - dnsZone
  - sniCertificate
- name: Deploys
  tags:
  - deploy
  - deployedBranch
  - deployKey
- name: Builds
  tags:
  - build
  - buildLogMsg
- name: Dev servers
  tags:
  - devServer
- name: Webhooks and notifications
  tags:
  - hook
  - hookType
  - buildHook
  - devServerHook
- name: Services
  tags:
  - service
  - serviceInstance
- name: Functions
  tags:
  - function
- name: Database
  tags:
  - database
- name: Forms
  tags:
  - form
  - submission
- name: Split tests
  tags:
  - splitTest
- name: Large media
  tags:
  - asset
  - assetPublicSignature
