openapi: 3.0.1
info:
  title: Netlify Netlify's API documentation accessToken splitTest API
  description: 'Netlify is a hosting service for the programmable web. It understands your documents and provides an API to handle atomic deploys of websites, manage form submissions, inject JavaScript snippets, and much more. This is a REST-style API that uses JSON for serialization and OAuth 2 for authentication.


    This document is an OpenAPI reference for the Netlify API that you can explore. For more detailed instructions for common uses, please visit the [online documentation](https://www.netlify.com/docs/api/). Visit our Community forum to join the conversation about [understanding and using Netlify’s API](https://community.netlify.com/t/common-issue-understanding-and-using-netlifys-api/160).


    Additionally, we have two API clients for your convenience:

    - [Go Client](https://github.com/netlify/open-api#go-client)

    - [JS Client](https://github.com/netlify/build/tree/main/packages/js-client)'
  termsOfService: https://www.netlify.com/legal/terms-of-use/
  version: 2.33.1
  x-logo:
    url: netlify-logo.png
    href: https://www.netlify.com/docs/
    altText: Netlify
servers:
- url: https://api.netlify.com/api/v1
security:
- netlifyAuth: []
tags:
- name: splitTest
  x-displayName: Split test
paths:
  /sites/{site_id}/traffic_splits:
    get:
      tags:
      - splitTest
      operationId: getSplitTests
      parameters:
      - name: site_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: split_tests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/splitTests'
        default:
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
    post:
      tags:
      - splitTest
      operationId: createSplitTest
      parameters:
      - name: site_id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/splitTestSetup'
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/splitTest'
        default:
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      x-codegen-request-body-name: branch_tests
  /sites/{site_id}/traffic_splits/{split_test_id}:
    get:
      tags:
      - splitTest
      operationId: getSplitTest
      parameters:
      - name: site_id
        in: path
        required: true
        schema:
          type: string
      - name: split_test_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: split_test
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/splitTest'
        default:
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
    put:
      tags:
      - splitTest
      operationId: updateSplitTest
      parameters:
      - name: site_id
        in: path
        required: true
        schema:
          type: string
      - name: split_test_id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/splitTestSetup'
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/splitTest'
        default:
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      x-codegen-request-body-name: branch_tests
  /sites/{site_id}/traffic_splits/{split_test_id}/publish:
    post:
      tags:
      - splitTest
      operationId: enableSplitTest
      parameters:
      - name: site_id
        in: path
        required: true
        schema:
          type: string
      - name: split_test_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: enable
          content: {}
        default:
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
  /sites/{site_id}/traffic_splits/{split_test_id}/unpublish:
    post:
      tags:
      - splitTest
      operationId: disableSplitTest
      parameters:
      - name: site_id
        in: path
        required: true
        schema:
          type: string
      - name: split_test_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: disabled
          content: {}
        default:
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
components:
  schemas:
    splitTestSetup:
      type: object
      properties:
        branch_tests:
          type: object
          properties: {}
    splitTest:
      type: object
      properties:
        id:
          type: string
        site_id:
          type: string
        name:
          type: string
        path:
          type: string
        branches:
          type: array
          items:
            type: object
            properties: {}
        active:
          type: boolean
        created_at:
          type: string
          format: dateTime
        updated_at:
          type: string
          format: dateTime
        unpublished_at:
          type: string
          format: dateTime
    error:
      required:
      - message
      type: object
      properties:
        code:
          type: integer
          format: int64
        message:
          type: string
          nullable: false
    splitTests:
      type: array
      items:
        $ref: '#/components/schemas/splitTest'
  securitySchemes:
    netlifyAuth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://app.netlify.com/authorize
          scopes: {}
externalDocs:
  description: Online documentation
  url: https://www.netlify.com/docs/api/
x-tagGroups:
- name: OAuth
  tags:
  - ticket
  - accessToken
- name: User accounts
  tags:
  - user
  - accountMembership
  - member
  - accountType
  - paymentMethod
  - auditLog
- name: Site
  tags:
  - site
  - environmentVariables
  - file
  - metadata
  - purge
  - snippet
- name: Domain names
  tags:
  - dnsZone
  - sniCertificate
- name: Deploys
  tags:
  - deploy
  - deployedBranch
  - deployKey
- name: Builds
  tags:
  - build
  - buildLogMsg
- name: Dev servers
  tags:
  - devServer
- name: Webhooks and notifications
  tags:
  - hook
  - hookType
  - buildHook
  - devServerHook
- name: Services
  tags:
  - service
  - serviceInstance
- name: Functions
  tags:
  - function
- name: Forms
  tags:
  - form
  - submission
- name: Split tests
  tags:
  - splitTest
- name: Large media
  tags:
  - asset
  - assetPublicSignature
x-original-swagger-version: '2.0'
