openapi: 3.2.0
info:
  version: 2.57.0
  title: Netlify's API documentation Hook API
  description: Netlify is a hosting service for the programmable web.
  termsOfService: https://www.netlify.com/legal/terms-of-use/
  x-logo:
    url: netlify-logo.png
    href: https://www.netlify.com/docs/
    altText: Netlify
servers:
- url: https://api.netlify.com/api/v1
security:
- netlifyAuth: []
tags:
- name: Hook
  x-displayName: Hook
paths:
  /hooks:
    get:
      operationId: listHooksBySiteId
      tags:
      - Hook
      parameters:
      - name: site_id
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    site_id:
                      type: string
                    type:
                      type: string
                    event:
                      type: string
                    data:
                      type: object
                    created_at:
                      type: string
                      format: dateTime
                    updated_at:
                      type: string
                      format: dateTime
                    disabled:
                      type: boolean
        default:
          description: error
          content:
            application/json:
              schema:
                type: object
                required:
                - message
                properties:
                  code:
                    type: integer
                    format: int64
                  message:
                    type: string
      summary: List hooks by site id
      x-summary-source: derived
    post:
      operationId: createHookBySiteId
      tags:
      - Hook
      parameters:
      - name: site_id
        in: query
        required: true
        schema:
          type: string
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  site_id:
                    type: string
                  type:
                    type: string
                  event:
                    type: string
                  data:
                    type: object
                  created_at:
                    type: string
                    format: dateTime
                  updated_at:
                    type: string
                    format: dateTime
                  disabled:
                    type: boolean
        default:
          description: error
          content:
            application/json:
              schema:
                type: object
                required:
                - message
                properties:
                  code:
                    type: integer
                    format: int64
                  message:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                site_id:
                  type: string
                type:
                  type: string
                event:
                  type: string
                data:
                  type: object
                created_at:
                  type: string
                  format: dateTime
                updated_at:
                  type: string
                  format: dateTime
                disabled:
                  type: boolean
        required: true
      summary: Create hook by site id
      x-summary-source: derived
  /hooks/{hook_id}:
    parameters:
    - name: hook_id
      in: path
      required: true
      schema:
        type: string
    get:
      operationId: getHook
      tags:
      - Hook
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  site_id:
                    type: string
                  type:
                    type: string
                  event:
                    type: string
                  data:
                    type: object
                  created_at:
                    type: string
                    format: dateTime
                  updated_at:
                    type: string
                    format: dateTime
                  disabled:
                    type: boolean
        default:
          description: error
          content:
            application/json:
              schema:
                type: object
                required:
                - message
                properties:
                  code:
                    type: integer
                    format: int64
                  message:
                    type: string
      summary: Get hook
      x-summary-source: derived
    put:
      operationId: updateHook
      tags:
      - Hook
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  site_id:
                    type: string
                  type:
                    type: string
                  event:
                    type: string
                  data:
                    type: object
                  created_at:
                    type: string
                    format: dateTime
                  updated_at:
                    type: string
                    format: dateTime
                  disabled:
                    type: boolean
        default:
          description: error
          content:
            application/json:
              schema:
                type: object
                required:
                - message
                properties:
                  code:
                    type: integer
                    format: int64
                  message:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                site_id:
                  type: string
                type:
                  type: string
                event:
                  type: string
                data:
                  type: object
                created_at:
                  type: string
                  format: dateTime
                updated_at:
                  type: string
                  format: dateTime
                disabled:
                  type: boolean
        required: true
      summary: Update hook
      x-summary-source: derived
    delete:
      operationId: deleteHook
      tags:
      - Hook
      responses:
        '204':
          description: No content
      summary: Delete hook
      x-summary-source: derived
  /hooks/{hook_id}/enable:
    parameters:
    - name: hook_id
      in: path
      required: true
      schema:
        type: string
    post:
      operationId: enableHook
      tags:
      - Hook
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  site_id:
                    type: string
                  type:
                    type: string
                  event:
                    type: string
                  data:
                    type: object
                  created_at:
                    type: string
                    format: dateTime
                  updated_at:
                    type: string
                    format: dateTime
                  disabled:
                    type: boolean
        default:
          description: error
          content:
            application/json:
              schema:
                type: object
                required:
                - message
                properties:
                  code:
                    type: integer
                    format: int64
                  message:
                    type: string
      summary: Enable hook
      x-summary-source: derived
components:
  securitySchemes:
    netlifyAuth:
      type: oauth2
      flows:
        implicit:
          scopes: {}
          authorizationUrl: https://app.netlify.com/authorize
externalDocs:
  url: https://www.netlify.com/docs/api/
  description: Online documentation
x-tagGroups:
- name: OAuth
  tags:
  - ticket
  - accessToken
- name: User accounts
  tags:
  - user
  - accountMembership
  - member
  - accountType
  - paymentMethod
  - auditLog
- name: Site
  tags:
  - site
  - environmentVariables
  - file
  - metadata
  - purge
  - snippet
- name: Domain names
  tags:
  - dnsZone
  - sniCertificate
- name: Deploys
  tags:
  - deploy
  - deployedBranch
  - deployKey
- name: Builds
  tags:
  - build
  - buildLogMsg
- name: Dev servers
  tags:
  - devServer
- name: Webhooks and notifications
  tags:
  - hook
  - hookType
  - buildHook
  - devServerHook
- name: Services
  tags:
  - service
  - serviceInstance
- name: Functions
  tags:
  - function
- name: Database
  tags:
  - database
- name: Forms
  tags:
  - form
  - submission
- name: Split tests
  tags:
  - splitTest
- name: Large media
  tags:
  - asset
  - assetPublicSignature
