naftiko: 1.0.0-alpha2
info:
  label: Netlify Netlify's API documentation — User
  description: 'Netlify Netlify''s API documentation — User. 1 operations. Lead operation: User. Self-contained Naftiko capability
    covering one Netlify business surface.'
  tags:
  - Netlify
  - User
  created: '2026-05-19'
  modified: '2026-05-19'
binds:
- namespace: env
  keys:
    NETLIFY_API_KEY: NETLIFY_API_KEY
capability:
  consumes:
  - type: http
    namespace: netlify-user
    baseUri: https://api.netlify.com/api/v1
    description: Netlify Netlify's API documentation — User business capability. Self-contained, no shared references.
    resources:
    - name: user
      path: /user
      operations:
      - name: getcurrentuser
        method: GET
        description: ''
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
    authentication:
      type: bearer
      token: '{{env.NETLIFY_API_KEY}}'
  exposes:
  - type: rest
    namespace: netlify-user-rest
    port: 8080
    description: REST adapter for Netlify Netlify's API documentation — User. One Spectral-compliant resource per consumed
      operation, prefixed with /v1.
    resources:
    - path: /v1/user
      name: user
      description: REST surface for user.
      operations:
      - method: GET
        name: getcurrentuser
        description: getcurrentuser
        call: netlify-user.getcurrentuser
        outputParameters:
        - type: object
          mapping: $.
  - type: mcp
    namespace: netlify-user-mcp
    port: 9090
    transport: http
    description: MCP adapter for Netlify Netlify's API documentation — User. One tool per consumed operation, routed inline
      through this capability's consumes block.
    tools:
    - name: getcurrentuser
      description: getcurrentuser
      hints:
        readOnly: true
        destructive: false
        idempotent: true
      call: netlify-user.getcurrentuser
      outputParameters:
      - type: object
        mapping: $.
