naftiko: 1.0.0-alpha2
info:
  label: Netlify Netlify's API documentation
  description: 'Netlify Netlify''s API documentation. 3 operations. Lead operation: General. Self-contained Naftiko capability
    covering one Netlify business surface.'
  tags:
  - Netlify
  created: '2026-05-19'
  modified: '2026-05-19'
binds:
- namespace: env
  keys:
    NETLIFY_API_KEY: NETLIFY_API_KEY
capability:
  consumes:
  - type: http
    namespace: netlify-general
    baseUri: https://api.netlify.com/api/v1
    description: Netlify Netlify's API documentation business capability. Self-contained, no shared references.
    resources:
    - name: services
      path: /services/
      operations:
      - name: getservices
        method: GET
        description: ''
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: search
          in: query
          type: string
    - name: services-addonName
      path: /services/{addonName}
      operations:
      - name: showservice
        method: GET
        description: ''
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: addonName
          in: path
          type: string
          required: true
    - name: services-addonName-manifest
      path: /services/{addonName}/manifest
      operations:
      - name: showservicemanifest
        method: GET
        description: ''
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: addonName
          in: path
          type: string
          required: true
    authentication:
      type: bearer
      token: '{{env.NETLIFY_API_KEY}}'
  exposes:
  - type: rest
    namespace: netlify-general-rest
    port: 8080
    description: REST adapter for Netlify Netlify's API documentation. One Spectral-compliant resource per consumed operation,
      prefixed with /v1.
    resources:
    - path: /v1/services
      name: services
      description: REST surface for services.
      operations:
      - method: GET
        name: getservices
        description: getservices
        call: netlify-general.getservices
        with:
          search: rest.search
        outputParameters:
        - type: object
          mapping: $.
    - path: /v1/services/{addonname}
      name: services-addonname
      description: REST surface for services-addonName.
      operations:
      - method: GET
        name: showservice
        description: showservice
        call: netlify-general.showservice
        with:
          addonName: rest.addonName
        outputParameters:
        - type: object
          mapping: $.
    - path: /v1/services/{addonname}/manifest
      name: services-addonname-manifest
      description: REST surface for services-addonName-manifest.
      operations:
      - method: GET
        name: showservicemanifest
        description: showservicemanifest
        call: netlify-general.showservicemanifest
        with:
          addonName: rest.addonName
        outputParameters:
        - type: object
          mapping: $.
  - type: mcp
    namespace: netlify-general-mcp
    port: 9090
    transport: http
    description: MCP adapter for Netlify Netlify's API documentation. One tool per consumed operation, routed inline through
      this capability's consumes block.
    tools:
    - name: getservices
      description: getservices
      hints:
        readOnly: true
        destructive: false
        idempotent: true
      call: netlify-general.getservices
      with:
        search: tools.search
      outputParameters:
      - type: object
        mapping: $.
    - name: showservice
      description: showservice
      hints:
        readOnly: true
        destructive: false
        idempotent: true
      call: netlify-general.showservice
      with:
        addonName: tools.addonName
      outputParameters:
      - type: object
        mapping: $.
    - name: showservicemanifest
      description: showservicemanifest
      hints:
        readOnly: true
        destructive: false
        idempotent: true
      call: netlify-general.showservicemanifest
      with:
        addonName: tools.addonName
      outputParameters:
      - type: object
        mapping: $.
